name: digit_flutter
repository: https://github.com/egovernments/health-campaign-field-worker-app

packages:
  - packages/*
  - apps/*

scripts:

  build_runner:
    exec: flutter packages run build_runner build --delete-conflicting-outputs
    select-package:
      no-select: true
      flutter: true
      depends-on: build_runner

  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.

  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.

  gen_coverage: melos exec -- "\$MELOS_ROOT_PATH/tools/combine_coverage.sh" && genhtml coverage_report/lcov.info -o coverage_report/html