name: health_campaigns_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  faker: ^2.0.0 # Library can be removed when no longer needed for fake data
  uuid: ^3.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.1
  freezed: ^2.1.0+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.0

flutter:
  uses-material-design: true