name: Build APK Workflow

on:
  push:
    branches:
      - hcmpre-717-github-actions-build-apk  # This specifies that the workflow will run on any push to the 'main' branch
  pull_request:
    branches:
      - hcmpre-717-github-actions-build-apk  # Optionally, run on pull requests targeting the 'main' branch

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Specify the Java distribution

      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: "3.16.5"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Install Dependencies
        run: flutter pub get

      - name: Run APK build script
        env:
          ENVIRONMENT: QA        # or UAT/DEV/ALL depending on your choice
          BUILD_CONFIG: release   # or profile depending on your choice
        run: yes 1 | bash ./tools/generate-apk.sh

      # Archive the APK as a build artifact so it can be downloaded
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk



#name: Build Flutter APK
#
#on:
#  push:
#    branches:
#      - hcmpre-717-github-actions-build-apk  # This specifies that the workflow will run on any push to the 'main' branch
#  pull_request:
#    branches:
#      - hcmpre-717-github-actions-build-apk  # Optionally, run on pull requests targeting the 'main' branch
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      # Checkout the latest code from the repository
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#
#      - name: Display working directory
#        run: pwd
#
#      - name: List files
#        run: ls -R
#
#      - name: Build release APK
#        working-directory: ./apps/health_campaign_field_worker_app/android
#        run: bash ./gradlew assembleRelease --stacktrace
#
#      - name: Build release APK
#        run: bash ./health_campaign_field_worker_app/android/gradlew assembleRelease --stacktrace
#
#      - name: Rename APK
#        run:
#          mv "./app/build/outputs/apk/release/app-release.apk" "./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk"
#
#      - name: Upload release APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: ${{ env.OUTPUT_NAME }}
#          path: app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk
#
#      - name: Build release AAB
#        run: bash ./gradlew bundleRelease --stacktrace
#
#      - name: Rename AAB
#        run:
#          mv "./app/build/outputs/bundle/release/app-release.aab" "./app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab"
#
#      - name: Upload debug AAB
#        uses: actions/upload-artifact@v1
#        with:
#          name: ${{ env.OUTPUT_NAME }}
#          path: app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab
