name: Build Flutter APK

on:
  push:
    branches:
      - hcmpre-717-github-actions-build-apk  # This specifies that the workflow will run on any push to the 'main' branch
  pull_request:
    branches:
      - hcmpre-717-github-actions-build-apk  # Optionally, run on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Flutter dependencies using the official Flutter GitHub action
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'

      # Run flutter pub get to fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      - name: Build debug APK
        run: ./tools/generate-apk.sh
      # Run flutter build apk to build the APK
      # Archive the APK as a build artifact so it can be downloaded
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: ./apps/health_campaign_field_worker_app/build/app/outputs/flutter-apk/app-release.apk
