# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run prepare for QA Workflow

on:
  push:
    branches: [ "qa" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        
      - name: Install melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: melos bs
        
      - name: Run tests
        run: melos run all-test
        
      - name: Build field-worker-app Android
        run: cd apps/health_campaign_field_worker_app && flutter build apk --release
        
      - name: Publish to Diawi
        run: curl -v --http1.1  https://upload.diawi.com/ -F token='lE6Qqe3Cv4nKPUVl2ZtiQpdulhQ5tZShQi3ia3rKB9' -F file=@/apps/health_campaign_field_worker_app/build/app/outputs/flutter-apk/app-release.apk -F find_by_udid=0 -F callback_emails='ajil.oommen@egovernments.org'
